name = "svelte-datagrid-docs"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm run build"

[assets]
directory = ".svelte-kit/cloudflare"
