name = "svelte-datagrid-docs"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Worker entry point
main = ".svelte-kit/cloudflare/_worker.js"

# Static assets binding
[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"
